"use server";

import { revalidatePath, revalidateTag } from "next/cache";

import {
  createSupabaseAdminClient,
  createSupabaseServerClient
} from "@/lib/supabase/server";

export type ProgramCreateInput = {
  title: string;
  description: string | null;
  level: string | null;
  methodology: string | null;
  isPublic: boolean;
  durationWeeks: number;
  daysPerWeek: number;
};

export type ProgramCreateResult = {
  ok: boolean;
  id?: string;
  slug?: string;
  error?: string;
};

async function requireAdminUserId(): Promise<string | null> {
  const client = createSupabaseServerClient();
  const {
    data: { user }
  } = await client.auth.getUser();
  if (!user) return null;
  const { data } = await client
    .from("users")
    .select("role")
    .eq("id", user.id)
    .maybeSingle<{ role: string }>();
  return data?.role === "admin" ? user.id : null;
}

/**
 * Creates a new program with basic info only.
 * Slug is auto-generated by the DB trigger `trg_programs_assign_slug`.
 * Week / Day / Exercise data is added later via seed SQL.
 */
export async function createProgram(
  input: ProgramCreateInput
): Promise<ProgramCreateResult> {
  const adminUserId = await requireAdminUserId();
  if (!adminUserId) return { ok: false, error: "forbidden" };

  const title = input.title.trim();
  if (!title) return { ok: false, error: "title_required" };

  const durationWeeks = Math.round(input.durationWeeks);
  const daysPerWeek = Math.round(input.daysPerWeek);
  if (durationWeeks < 1 || durationWeeks > 52) {
    return { ok: false, error: "invalid_duration_weeks" };
  }
  if (daysPerWeek < 1 || daysPerWeek > 7) {
    return { ok: false, error: "invalid_days_per_week" };
  }

  const validLevels = ["beginner", "intermediate", "advanced"];
  const level = input.level && validLevels.includes(input.level) ? input.level : null;

  const validMethodologies = ["gzcl", "linear", "generic"];
  const methodology =
    input.methodology && validMethodologies.includes(input.methodology)
      ? input.methodology
      : null;

  const admin = createSupabaseAdminClient();

  const { data: inserted, error: insertErr } = await admin
    .from("programs")
    .insert({
      creator_user_id: adminUserId,
      title,
      description: input.description?.trim() || null,
      level,
      methodology,
      is_public: input.isPublic,
      duration_weeks: durationWeeks,
      days_per_week: daysPerWeek
    })
    .select("id, slug")
    .maybeSingle<{ id: string; slug: string }>();

  if (insertErr || !inserted) {
    console.error("createProgram: insert failed", insertErr?.message);
    return { ok: false, error: insertErr?.message ?? "insert_failed" };
  }

  revalidateTag("program-library");
  revalidatePath("/programs");
  revalidatePath("/admin/programs");

  return { ok: true, id: inserted.id, slug: inserted.slug };
}
